# Generated by Django 5.0.1 on 2025-04-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
